### PR TITLE
fix: null range on DocumentSymbolData

### LINKED ISSUE #830: Exception when shift+shift
Exception:
```java
java.lang.IllegalArgumentException: text range null for {CACHED_SMART_POINTER_KEY=java.lang.ref.SoftReference@409f639b}; class com.redhat.devtools.lsp4ij.features.documentSymbol.DocumentSymbolData
	at com.intellij.usageView.UsageInfo.<init>(UsageInfo.java:38)
	at com.intellij.usageView.UsageInfo.<init>(UsageInfo.java:121)
	at com.intellij.usageView.UsageInfo.<init>(UsageInfo.java:149)
	at com.intellij.ide.actions.searcheverywhere.PreviewPrimaryUsageFinderImpl.findPrimaryUsageInfo(SearchEverywherePreviewPrimaryUsageFinder.kt:40)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$14.findFirstChild(SearchEverywhereUI.java:1088)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$14.lambda$run$0(SearchEverywhereUI.java:1037)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:314)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:262)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:66)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$14.run(SearchEverywhereUI.java:1036)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

LSP communication:
```javascript
[Trace - 10:58:01] Sending request 'textDocument/documentSymbol - (22)'.
Params: {
  "textDocument": {
    "uri": "file:///home/greg/dev/clojure-sample/src/clojure_sample/foo.clj"
  }
}


[Trace - 10:58:01] Received response 'textDocument/documentSymbol - (22)' in 7ms.
Result: [
  {
    "name": "clojure-sample.foo",
    "kind": 3,
    "range": {
      "start": {
        "line": 0,
        "character": 0
      },
      "end": {
        "line": 0,
        "character": 23
      }
    },
    "selectionRange": {
      "start": {
        "line": 0,
        "character": 4
      },
      "end": {
        "line": 0,
        "character": 22
      }
    },
    "tags": []
  },
  {
    "name": "empty-project",
    "kind": 13,
    "range": {
      "start": {
        "line": 32,
        "character": 0
      },
      "end": {
        "line": 50,
        "character": 12
      }
    },
    "selectionRange": {
      "start": {
        "line": 32,
        "character": 15
      },
      "end": {
        "line": 32,
        "character": 28
      }
    },
    "detail": "private",
    "tags": []
  }
]


```

### PR DESCRIPTION
**Pull request by ericdallo**
Fixes #830

### CODE REVIEW

File: src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/DocumentSymbolData.java [hunk 1]
```diff
@@ -76,6 +79,11 @@ public int getTextOffset() {
         return getClientFeatures().getDocumentSymbolFeature().getTextOffset(documentSymbol, psiFile);
     }
 
+    @Override
+    public TextRange getTextRange() {
+        return LSPIJUtils.toTextRange(documentSymbol.getRange(), LSPIJUtils.getDocument(psiFile.getVirtualFile()));
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/DocumentSymbolData.java:84]: I will store the text range is a field, since I suppose this method can be called several times.

Comment (ericdallo) [reply src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/DocumentSymbolData.java]: Done

File: src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/DocumentSymbolData.java [hunk 2]
```diff
@@ -53,6 +54,7 @@ public DocumentSymbolData(@NotNull DocumentSymbol documentSymbol,
         this.psiFile = psiFile;
         this.languageServer = languageServer;
         this.parent = parent;
+        this.textRange = LSPIJUtils.toTextRange(documentSymbol.getRange(), LSPIJUtils.getDocument(psiFile.getVirtualFile()));
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/DocumentSymbolData.java:57]: Don't compute this textRange is the constructor since this text range could ne not used, but compute it if the method getTextRange is called.

```java
Override
public TextRange getTextRange() {
    if (textRange == null) {
        textRange = LSPIJUtils.toTextRange(documentSymbol.getRange(), LSPIJUtils.getDocument(psiFile.getVirtualFile()));
   }
    return textRange;
}
```

**Comment by angelozerr** [comment]
Thanks @ericdallo !
