### PR TITLE
fix: Allow requesting flat scalar values in workspace/configuration

### LINKED ISSUE #746: workspace/configuration does not work when section contains dot.
Image

Image

```kotlin
data class Setting(
    @SerializedName("JimmerDTO.Classpath.FindBuilder")
    var classpathFindBuilder: Boolean = true,
    @SerializedName("JimmerDTO.Classpath.FindConfiguration")
    var classpathFindConfiguration: Boolean = true,
    @SerializedName("JimmerDTO.Classpath.FindOtherProject")
    var classpathFindOtherProject: Boolean = true
)
```

```kotlin
override fun createLanguageClient(project: Project): LanguageClientImpl {
    return object : LanguageClientImpl(project) {
        override fun createSettings(): Any {
            return Gson().toJsonTree(PluginSetting.INSTANCE.state).asJsonObject
        }
    }
}
```

### PR DESCRIPTION
**Pull request by Enaium**
Fixes #746

### CODE REVIEW

File: src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java [hunk 1]
```diff
@@ -249,7 +249,11 @@ protected Object findSettings(@Nullable String section) {
                 return config;
             }
             String[] sections = section.split("[.]");
-            return findSettings(sections, json);
+            Object settings = findSettings(sections, json);
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java:252]: It would be nice to move this fix inside SettingsHelper and write tests with this usecase in https://github.com/redhat-developer/lsp4ij/blob/main/src/test/java/com/redhat/devtools/lsp4ij/client/SettingsHelperTest.java

File: src/test/java/com/redhat/devtools/lsp4ij/client/SettingsHelperTest.java [hunk 2]
```diff
@@ -35,26 +35,22 @@ public class SettingsHelperTest extends BasePlatformTestCase {
...
-        JsonElement result = SettingsHelper.findSettings(sections, jsonObject);
+        JsonElement result = SettingsHelper.findSettings(section, jsonObject);
 
         assertEquals(result, expectedJson);
     }
 
-    public void testGetSettingsIdentityOnEmptySections() {
-        String[] requestedPath = new String[0];
-        assertFindSettings(testJson, requestedPath, testJson);
-    }
```
Comment (Enaium) [inline src/test/java/com/redhat/devtools/lsp4ij/client/SettingsHelperTest.java:54]: string array is never empty

File: src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java [hunk 3]
```diff
@@ -248,14 +248,13 @@ protected Object findSettings(@Nullable String section) {
             if (section == null) {
                 return config;
             }
-            String[] sections = section.split("[.]");
```
Comment (Enaium) [inline src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java:251]: string array is never empty

**Comment by angelozerr** [comment]
Thanks so much, it looks great!

Last thing, could you add a new tests with your language server and write 3 tests:

 * one test with `JimmerDTO` section
 * one test with `JimmerDTO.Classpath` section
 * one test with `JimmerDTO.Classpath.FindBuilder` section

Having those 3 tests will be nice to have a concrete sample.

File: src/test/java/com/redhat/devtools/lsp4ij/client/SettingsHelperTest.java [hunk 4]
```diff
@@ -35,26 +35,25 @@ public class SettingsHelperTest extends BasePlatformTestCase {
                         "subsettingA": 1,
                         "subsettingB": 2
                     }
-                }
+                },
+                "flat.scalar.value": "flat value",
+                "flat.scalar.value2": "flat value2",
+                "JimmerDTO.Classpath.FindBuilder": false,
+                "JimmerDTO.Classpath.FindConfiguration": false
```
Comment (angelozerr) [inline src/test/java/com/redhat/devtools/lsp4ij/client/SettingsHelperTest.java:42]: Please add `"JimmerDTO.CLasspath.FindOtherProject": false`

**Comment by angelozerr** [comment]
Thanks @Enaium !
