### PR TITLE
fix: Ensure DocumentContentSynchronizer is always disposed

### LINKED ISSUE #1360: Memory leak detected in DocumentContentSynchronizer
```
2025-11-03 16:06:08,238 [ 923040] SEVERE - #c.i.o.u.ObjectTree - Memory leak detected: 'com.redhat.devtools.lsp4ij.DocumentContentSynchronizer@cb060a8' (class com.redhat.devtools.lsp4ij.DocumentContentSynchronizer) was registered in Disposer as a child of 'ROOT_DISPOSABLE' (class com.intellij.openapi.util.Disposer$2) but wasn't disposed.
Register it with a proper 'parentDisposable' or ensure that it's always disposed by direct Disposer.dispose() call.
See https://plugins.jetbrains.com/docs/intellij/disposers.html for more details.
The corresponding Disposer.register() stacktrace is shown as the cause:

java.lang.RuntimeException: Memory leak detected: 'com.redhat.devtools.lsp4ij.DocumentContentSynchronizer@cb060a8' (class com.redhat.devtools.lsp4ij.DocumentContentSynchronizer) was registered in Disposer as a child of 'ROOT_DISPOSABLE' (class com.intellij.openapi.util.Disposer$2) but wasn't disposed.
Register it with a proper 'parentDisposable' or ensure that it's always disposed by direct Disposer.dispose() call.
See https://plugins.jetbrains.com/docs/intellij/disposers.html for more details.
The corresponding Disposer.register() stacktrace is shown as the cause:

	at com.intellij.openapi.util.ObjectNode.assertNoChildren(ObjectNode.java:47)
	at com.intellij.openapi.util.ObjectTree.assertIsEmpty(ObjectTree.java:227)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:228)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:222)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeContainer(ApplicationImpl.java:280)
	at com.intellij.openapi.application.impl.ApplicationImpl.destructApplication(ApplicationImpl.java:845)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:741)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:726)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:715)
	at com.intellij.openapi.application.ex.ApplicationEx.exit(ApplicationEx.java:65)
	at com.intellij.ide.actions.ExitAction.actionPerformed(ExitAction.java:32)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.kt:437)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performAction$lambda$0(ActionUtil.kt:397)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks$lambda$0(ActionManagerImpl.kt:1164)
	at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:305)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1162)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performAction(ActionUtil.kt:396)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction$lambda$0(ActionMenuItem.kt:269)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:234)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.kt:262)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem._init_$lambda$0(ActionMenuItem.kt:71)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed$lambda$0(ActionMenuItem.kt:102)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:98)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.kt:101)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:521)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:554)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6679)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3394)
	at java.desktop/java.awt.Component.processEvent(Component.java:6444)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5049)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4877)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4577)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2823)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4877)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:664)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$2(IdeEventQueue.kt:508)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.doRunWriteIntentReadAction(NestedLocksThreadingSupport.kt:737)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.runPreventiveWriteIntentReadAction(NestedLocksThreadingSupport.kt:711)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:508)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0$0$0$0(IdeEventQueue.kt:337)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:897)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0$0$0(IdeEventQueue.kt:336)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1065)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:117)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1065)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0(IdeEventQueue.kt:331)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:371)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.Throwable
	at com.intellij.openapi.util.ObjectNode.<init>(ObjectNode.java:25)
	at com.intellij.openapi.util.ObjectNode.findOrCreateChildNode(ObjectNode.java:150)
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:52)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:162)
	at com.intellij.util.Alarm.<init>(Alarm.kt:154)
	at com.intellij.util.Alarm.<init>(Alarm.kt:46)
Disconnected from the target VM, address: 'localhost:52002', transport: 'socket'
	at com.intellij.util.Alarm.<init>(Alarm.kt:104)
	at com.redhat.devtools.lsp4ij.DocumentContentSynchronizer.getDebouncePullDiagnosticsAlarm(DocumentContentSynchronizer.java:444)
	at com.redhat.devtools.lsp4ij.DocumentContentSynchronizer.processPullDiagnosticIfNeeded(DocumentContentSynchronizer.java:359)
	at com.redhat.devtools.lsp4ij.DocumentContentSynchronizer.getDidOpenFutureSync(DocumentContentSynchronizer.java:131)
	at com.redhat.devtools.lsp4ij.DocumentContentSynchronizer.getDidOpenFuture(DocumentContentSynchronizer.java:86)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$connect$16(LanguageServerWrapper.java:671)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
2025-11-03 16:06:08,240 [ 923042] SEVERE - #c.i.o.u.ObjectTree - IntelliJ IDEA 2025.3 EAP  Build #IU-253.27864.23

```

### PR DESCRIPTION
**Pull request by eliseevh**
Fixes #1360

### CODE REVIEW

**Comment by angelozerr** [comment]
Thanks so much @eliseevh !

Let me try your PR

File: src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java [hunk 1]
```diff
@@ -766,8 +770,7 @@ void disconnect(@Nullable URI fileUri, boolean stopIfNoOpenedFiles) {
             // Remove the listener from the old document stored in synchronizer
             DocumentContentSynchronizer synchronizer = openedDocument.getSynchronizer();
             if (synchronizer != null) {
-                synchronizer.getDocument().removeDocumentListener(synchronizer);
-                synchronizer.dispose();
+                Disposer.dispose(synchronizer);
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java]: Why you have removed removeDocumentListener ?
