### PR TITLE
fix: compare two filenames before trying to rename the file

### LINKED ISSUE #577: Diagnostics is not showing in server.env file
Following the update to LSP4IJ 0.4.0, one of our GHA UI test (GradleSingleModLSTest > testDiagnosticInServerEnv()) has been consistently failing on Windows. Upon investigation, we discovered that the issue has been occurring since the nightly build version [0.4.0-20240814-141029](https://plugins.jetbrains.com/plugin/23257-lsp4ij/versions/nightly/587545)

image

LTI build with LSP4IJ version 0.4.0-20240814-141029(Aug 14) - https://github.com/aparnamichael/liberty-tools-intellij/actions/runs/11123067607

LTI build with LSP4IJ version 0.4.0-20240813-173701(Aug 13) - https://github.com/aparnamichael/liberty-tools-intellij/actions/runs/11123925619

LTI build with LSP4IJ version[0.4.0-20240815-013110(Aug 15) - https://github.com/aparnamichael/liberty-tools-intellij/actions/runs/11124525639

I created a fork of the lsp4ij repository and set up a branch (https://github.com/aparnamichael/lsp4ij/tree/lsp4ij-test), where I reverted a [commit](https://github.com/redhat-developer/lsp4ij/commit/aaf8a1c2ed5704f096462da5d46bbe2d2ef55e1e) from August 14. After running an LTI build with these changes, the GHA UI test consistently succeeded.

LTI build ran using the LSP4IJ from https://github.com/aparnamichael/lsp4ij/tree/lsp4ij-test -> https://github.com/aparnamichael/liberty-tools-intellij/actions/runs/11346287359/job/31555011172

As a temporary fix for the UI test failure, we've implemented a workaround. Before checking for diagnostics, we close and reopen the `server.env` file, which triggers the diagnostics to appear and allows the test to pass successfully. Since the reverted commit in my lsp4ij branch is also related to file operations, could you please help us to identify the issue? 

Also, it would be helpful if you could provide some details about the changes related to file listeners and operations in this [commit](https://github.com/redhat-developer/lsp4ij/commit/aa384fbfb7c2d57f3bd468e2cae673e65bdcf805) .

### PR DESCRIPTION
**Pull request by turkeylurkey**
Compare the oldValue to the newValue. In the case of a file name change only execute the rename code if the two names are different. 

Fixes #577

### CODE REVIEW

File: src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java [hunk 1]
```diff
@@ -69,15 +69,22 @@ public void fileClosed(@NotNull FileEditorManager source, @NotNull VirtualFile f
     @Override
     public void propertyChanged(@NotNull VirtualFilePropertyEvent event) {
         if (event.getPropertyName().equals(VirtualFile.PROP_NAME) && event.getOldValue() instanceof String) {
+            String oldValue = (String) event.getOldValue();
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java:72]: To simplify code, I will write:

```java
if (event.getPropertyName().equals(VirtualFile.PROP_NAME) && 
                event.getOldValue() instanceof String oldValue &&
                event.getNewValue() instanceof String newValue) {
```

File: src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java [hunk 2]
```diff
@@ -69,15 +69,22 @@ public void fileClosed(@NotNull FileEditorManager source, @NotNull VirtualFile f
...
     public void propertyChanged(@NotNull VirtualFilePropertyEvent event) {
         if (event.getPropertyName().equals(VirtualFile.PROP_NAME) && event.getOldValue() instanceof String) {
+            String oldValue = (String) event.getOldValue();
+            String newValue = null;
             // A file (Test1.java) has been renamed (to Test2.java) by using Refactor / Rename from IJ
+            // or a "properties" file is changed or saved.
+            if (event.getNewValue() instanceof String) {
+                newValue = (String) event.getNewValue();
+            }
+            if (!oldValue.equals(newValue)) {
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java:79]: To avoid NPE with oldValue. I will compare old and new value with Objects.equals(oldValue, newValue)

File: src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java (hunk 1 above)
Comment (angelozerr) [reply src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java:72]: I will move this code in a new static private method to write:

....java
public void propertyChanged(@NotNull VirtualFilePropertyEvent event) {
  if (!isRenameFile(event)) {
    return;
  }
  ....
}

private static boolean isRenameFile(@NotNull VirtualFilePropertyEvent event) {
  if (event.getPropertyName().equals(VirtualFile.PROP_NAME) && 
                event.getOldValue() instanceof String oldValue &&
                event.getNewValue() instanceof String newValue) {
    return Objects.equals(oldValue, newValue);
  }
  return false;
}
....

**Comment by angelozerr** [comment]
Thanks @turkeylurkey !

Just to have some confirmation. Is this PR fixes your test problem?

**Comment by turkeylurkey** [comment]
Yes, I'm pretty sure it will based on local testing. Thank you.

File: src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java [hunk 3]
```diff
@@ -68,17 +68,27 @@ public void fileClosed(@NotNull FileEditorManager source, @NotNull VirtualFile f
...
+        moveFile(oldFileUri, newFile);
+    }
 
-            // 2. Send a workspace/didChangeWatchedFiles
-            moveFile(oldFileUri, newFile);
+    private static boolean isRenameFile(@NotNull VirtualFilePropertyEvent event) {
+        if (event.getPropertyName().equals(VirtualFile.PROP_NAME) &&
+                event.getOldValue() instanceof String oldValue &&
+                event.getNewValue() instanceof String newValue) {
+            return Objects.equals(oldValue, newValue);
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java:89]: return !Objects.equals(oldValue, newValue);

Comment (turkeylurkey) [reply src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java]: Good suggestion, makes better sense now.

File: src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java [hunk 4]
```diff
@@ -68,17 +68,27 @@ public void fileClosed(@NotNull FileEditorManager source, @NotNull VirtualFile f
 
     @Override
     public void propertyChanged(@NotNull VirtualFilePropertyEvent event) {
-        if (event.getPropertyName().equals(VirtualFile.PROP_NAME) && event.getOldValue() instanceof String) {
-            // A file (Test1.java) has been renamed (to Test2.java) by using Refactor / Rename from IJ
+        // Either a file (Test1.java) has been renamed (to Test2.java) by using Refactor / Rename from IJ
+        // or a "properties" file is changed or saved.
+        if (isRenameFile(event)) {
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java:73]: `if (!isRenameFile(event)) {`

Comment (angelozerr) [reply src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java:73]: Once you will fix that, I think the PR can be merged.

It would be really nice to write tests with this usecase but I need to find time to write them.

Comment (turkeylurkey) [reply src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java:73]: Agreed, I reformatted the code also.

Comment (turkeylurkey) [reply src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java:73]: I tested this with our tools to make sure this change is correct.

**Comment by angelozerr** [comment]
Thanks @turkeylurkey !
