### PR TITLE
fix: render notifications as clickable HTML

### LINKED ISSUE #80: Markdown notifications don't render properly
I tried the [Rust Analyzer](https://rust-analyzer.github.io/) LS and saw this notification immediately (as I have no idea on how to properly configure it). The Markdown link is rendered as plain text.

Screenshot 2024-01-11 at 14 32 57

### PR DESCRIPTION
**Pull request by fbricon**
Notifications from LS are rendered as HTML, hyperlinks are clickable:

Screenshot 2024-01-15 at 10 30 07

Fixes #80

### CODE REVIEW

File: src/main/java/com/redhat/devtools/lsp4ij/ServerMessageHandler.java [hunk 1]
```diff
@@ -54,7 +57,7 @@ private static NotificationType messageTypeToNotificationType(MessageType type)
 
 
     public static void showMessage(String title, MessageParams params) {
-        Notification notification = new Notification("Language Server Protocol", title, params.getMessage(), messageTypeToNotificationType(params.getType()));
+        Notification notification = new Notification("Language Server Protocol", title, toHTML(params.getMessage()), messageTypeToNotificationType(params.getType()), NotificationListener.URL_OPENING_LISTENER);
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/lsp4ij/ServerMessageHandler.java:60]: Use bundle message for `Language Server Protocol`

Comment (fbricon) [reply src/main/java/com/redhat/devtools/lsp4ij/ServerMessageHandler.java]: done
