### PR TITLE
fix: properly render markdown tables

### LINKED ISSUE #58: NPE in LSPDocumentationProvider.generateDoc
When writing/selecting javadoc in a Java class, I stumbled upon this twice:

```
Unhandled exception in [CoroutineName(DocumentationBrowser requests), CoroutineId(569), "DocumentationBrowser requests#569":StandaloneCoroutine{Cancelling}@351eda1e, Dispatchers.Default]

java.lang.NullPointerException: Cannot invoke "com.intellij.psi.PsiElement.getContainingFile()" because "originalElement" is null
	at com.redhat.devtools.lsp4ij.operations.documentation.LSPDocumentationProvider.generateDoc(LSPDocumentationProvider.java:73)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:135)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDocHtml(PsiElementDocumentationTarget.kt:102)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDoc(PsiElementDocumentationTarget.kt:88)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.computeDocumentation(PsiElementDocumentationTarget.kt:75)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentation$2$documentationResult$1.invoke(impl.kt:31)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentation$2$documentationResult$1.invoke(impl.kt)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:96)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:13)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:81)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:13)
	at com.intellij.openapi.progress.CancellationKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(cancellation.kt)
	at com.intellij.openapi.progress.Cancellation.withJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withJob(cancellation.kt:14)
	at com.intellij.openapi.progress.CancellationKt.executeWithJobAndCompleteIt(cancellation.kt:111)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$2$1.run(cancellableReadAction.kt:33)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$2.run(cancellableReadAction.kt:31)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:29)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:80)
	at com.intellij.openapi.application.rw.InternalReadAction.access$tryReadCancellable(InternalReadAction.kt:13)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:66)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:13)
	at com.intellij.openapi.progress.CancellationKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(cancellation.kt)
	at com.intellij.openapi.progress.Cancellation.withJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withJob(cancellation.kt:14)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:138)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:61)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:53)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:13)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:33)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:32)
	at com.intellij.openapi.application.rw.PlatformReadActionSupport.executeReadAction(PlatformReadActionSupport.kt:24)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:47)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:17)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentation$2.invokeSuspend(impl.kt:30)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentation$2.invoke(impl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.lang.documentation.impl.ImplKt.computeDocumentation(impl.kt:29)
	at com.intellij.lang.documentation.ide.impl.DocumentationPage.loadPage(DocumentationPage.kt:32)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.handleBrowserRequest(DocumentationBrowser.kt:91)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.access$handleBrowserRequest(DocumentationBrowser.kt:24)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invokeSuspend(DocumentationBrowser.kt:51)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invoke(DocumentationBrowser.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:217)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1.emit(Collect.kt:140)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:351)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:101)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.flow.internal.FlowCoroutineKt.flowScope(FlowCoroutine.kt:33)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:25)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### PR DESCRIPTION
**Pull request by fbricon**
Before:
Screenshot 2023-12-19 at 12 07 11

After:
Screenshot 2023-12-19 at 15 14 04

Also fixes #58 

Signed-off-by: Fred Bricon <fbricon@gmail.com>

### CODE REVIEW

File: src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProvider.java [hunk 1]
```diff
@@ -70,15 +98,15 @@ public String getQuickNavigateInfo(PsiElement element, PsiElement originalElemen
     @Nullable
     @Override
     public String generateDoc(@NotNull PsiElement element, @Nullable PsiElement originalElement) {
-        if (!LanguageServersRegistry.getInstance().isLanguageSupported(originalElement.getContainingFile())) {
+        if (originalElement == null || !LanguageServersRegistry.getInstance().isLanguageSupported(originalElement.getContainingFile())) {
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProvider.java:101]: I will remove this condition and move to line 118 since this hover provider is used for completion documentation.

File: src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProvider.java [hunk 2]
```diff
@@ -107,16 +132,20 @@ public String generateDoc(@NotNull PsiElement element, @Nullable PsiElement orig
...
-            return styleHtml(editor, RENDERER.render(PARSER.parse(s)));
+            return styleHtml(editor, toHTML(s));
         } finally {
             if (originalElement != null) {
                 originalElement.putUserData(TARGET_OFFSET_KEY, null);
             }
         }
     }
 
+    public @NotNull String toHTML(@NotNull String markdown) {
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProvider.java:145]: I think it should be better to move this method in a MarkdownConverter class and write test on MarkdownConverter.

Perhaps MarkdownConverter  could be used in an another location?

File: src/test/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProviderTest.java [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+                <tr><th> </th><th> </th></tr>
+                </thead>
+                <tbody>
+                <tr><td>Row One - Cell One</td><td>Row One - Cell Two</td></tr>
+                <tr><td>Row Two - Cell One</td><td>Row Two - Cell Two</td></tr>
+                </tbody>
+                </table>
+                """;
+        assertEquals(expected, docProvider.toHTML(markdown));
+    }
```
Comment (angelozerr) [inline src/test/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProviderTest.java:53]: Could you please write other tests with other html elements like <p>, <b>, <i>, etc like we have https://github.com/eclipse/lemminx/blob/main/org.eclipse.lemminx/src/test/java/org/eclipse/lemminx/utils/MarkdownConverterTest.java (but perhaps by splitti,g them in several tests)

Could you write too a simple text with hyperlink. I have not a usecase in my mind, but perhaps we should support baseURI in the future, If we have one test with hyperlink we will able to adapt it with baseURI

Do you know if the converter could support github syntax for code (ex {'''xml)), but I think we need to integrate that with IJ and textmate (I did that in eclipse tm4e markdown support).

File: src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProvider.java (hunk 2 above)
Comment (fbricon) [reply src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProvider.java]: done

File: src/test/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProviderTest.java (hunk 3 above)
Comment (fbricon) [reply src/test/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProviderTest.java]: done

File: src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/MarkdownConverter.java [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+import com.vladsch.flexmark.ext.tables.TablesExtension;
+import com.vladsch.flexmark.html.HtmlRenderer;
+import com.vladsch.flexmark.parser.Parser;
+import com.vladsch.flexmark.util.data.MutableDataSet;
+import org.jetbrains.annotations.NotNull;
+
+import java.util.Arrays;
+
+/**
+ * Converts Mardown to HTML
```
Comment (angelozerr) [inline src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/MarkdownConverter.java:24]: Markdown

**Comment by angelozerr** [comment]
It works like a charm, great job @fbricon !
